

List<Map<String, dynamic>> contriesStripe(){
 return [
 { "name": "Australia", "indicative-code": "268" },
 { "name": "Austria", "indicative-code": "268" },
 { "name": "Belgium", "indicative-code": "268" },
 { "name": "Brazil", "indicative-code": "268" },
 { "name": "Bulgaria", "indicative-code": "268" },
 { "name": "Canada", "indicative-code": "268" },
 { "name": "Cyprus", "indicative-code": "268" },
 { "name": "Czech Republic", "indicative-code": "268" },
 { "name": "Denmark", "indicative-code": "268" },
 { "name": "Estonia", "indicative-code": "268" },
 { "name": "Finland", "indicative-code": "268" },
 { "name": "France", "indicative-code": "268" },
 { "name": "Germany", "indicative-code": "268" },
 { "name": "Greece", "indicative-code": "268" },
 { "name": "Hong Kong", "indicative-code": "268" },
 { "name": "Hungary", "indicative-code": "268" },
 { "name": "India", "indicative-code": "268" },
 { "name": "Ireland", "indicative-code": "268" },
 { "name": "Italy", "indicative-code": "268" },
 { "name": "Japan", "indicative-code": "268" },
 { "name": "Latvia", "indicative-code": "268" },
 { "name": "Lithuania", "indicative-code": "268" },
 { "name": "Luxembourg", "indicative-code": "268" },
 { "name": "Malta", "indicative-code": "268" },
 { "name": "Mexico", "indicative-code": "268" },
 { "name": "Netherlands", "indicative-code": "268" },
 { "name": "New Zealand", "indicative-code": "268" },
 { "name": "Norway", "indicative-code": "268" },
 { "name": "Poland", "indicative-code": "268" },
 { "name": "Portugal", "indicative-code": "268" },
 { "name": "Romania", "indicative-code": "268" },
 { "name": "Singapore", "indicative-code": "268" },
 { "name": "Slovakia", "indicative-code": "268" },
 { "name": "Slovenia", "indicative-code": "268" },
 { "name": "Spain", "indicative-code": "268" },
 { "name": "Sweden", "indicative-code": "268" },
 { "name": "Switzerland", "indicative-code": "268" },
 { "name": "United Kingdom", "indicative-code": "268" },
 { "name": " United States", "indicative-code": "268" }
 ];
}