name: maando
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1s

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  adaptive_dialog: ^1.1.0
  animate_do: ^2.0.0 
  shared_preferences: ^2.0.8 
  http: ^0.13.3
  provider: ^6.0.1
  rxdart: ^0.26.0
  flutter_swiper: ^1.1.6
  local_auth: ^1.1.8
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  google_sign_in: ^5.1.1
  google_sign_in_web: ^0.10.0+3
  flutter_facebook_auth: ^3.5.1
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  geolocator: ^7.6.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  auth_buttons: ^1.0.1+4
  fluttertoast: ^8.0.7
  image_picker: ^0.8.4+2
  avatar_view: ^1.0.1
  intl: ^0.17.0
  direct_select: ^2.0.0
  share: ^2.0.4
  rflutter_alert: ^2.0.4
  connectivity: ^3.0.6
  webfeed: ^0.7.0 
  url_launcher: ^6.0.12
  firebase_messaging: ^11.1.0
  path_provider: ^2.0.5
  sign_in_with_apple: ^3.2.0
  flutter_keyboard_visibility: ^5.0.3
  firebase_storage: ^10.2.5
  objectid: ^2.0.0
  http_auth: ^1.0.1
  webview_flutter: ^2.1.1
  flutter_webview_plugin:
    git: https://github.com/nuc134r/flutter_webview_plugin.git
  platform_action_sheet: ^0.0.3
  socket_io_client: ^1.0.1
  permission_handler: ^8.1.6
  google_maps_flutter: ^2.0.10
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^0.22.0
  mongo_dart: ^0.7.2
  uuid: ^3.0.5
  flutter_easyloading: ^3.0.0
  quiver: ^3.0.1
  photo_view: ^0.13.0
  cached_network_image: ^3.1.0
  dash_chat: ^1.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter
      # solo temporal verificar si ya no es necesario
  material_design_icons_flutter: ^4.0.5955
  rulers: "^1.0.3"
  

  flutter_launcher_icons:

flutter_icons:
 android: "launcher_icon"
 ios: true
 image_path: "assets/icon/logo-1024x1024.png"
 adaptive_icon_background: "assets/icon/logo-1024x1024.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/face_1/
    - assets/images/touch_1/
    - assets/images/google/
    - assets/images/sidebar/
    - assets/images/page/
    - assets/images/close/
    - assets/images/onboarding/
    - assets/images/general/
    - assets/images/post/
    - assets/images/box/
    - assets/images/paymethods/
    - assets/images/popup/es/
    - assets/images/popup/en/
    - assets/icon/maando.svg
    - assets/icon/
    # - assets/videos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Exprswy
      fonts:
        - asset: assets/fonts/expresswayrg.ttf
        
          # style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
